name: flutter_course
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  bloc: ^8.1.3
  cached_network_image: ^3.3.1
  dio: ^5.4.1
  drift: ^2.16.0
  equatable: ^2.0.5
  firebase_core: ^2.31.1
  firebase_messaging: ^14.9.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_local_notifications: ^17.1.2
  flutter_localizations:
    sdk: flutter
  geolocator: ^11.0.0
  http: ^1.2.1
  intl: any
  path: ^1.9.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  sqlite3_flutter_libs: ^0.5.20
  yandex_mapkit: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  drift_dev: ^2.16.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
