// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU2K1lzRWP2TiC56gRsPD8TNAaVNP9N6Y',
    appId: '1:354401716290:web:e631e9d45e3940afee45db',
    messagingSenderId: '354401716290',
    projectId: 'coffee-shop-app-d909c',
    authDomain: 'coffee-shop-app-d909c.firebaseapp.com',
    storageBucket: 'coffee-shop-app-d909c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVcMw7Nb7DxVWw6Q90vELxDpYavnFUU6k',
    appId: '1:354401716290:android:54aed4dfc47e550dee45db',
    messagingSenderId: '354401716290',
    projectId: 'coffee-shop-app-d909c',
    storageBucket: 'coffee-shop-app-d909c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr2-f_KC2BjnzkfW611zO3VPsRWcAp6_s',
    appId: '1:354401716290:ios:66b94d3eec26ad00ee45db',
    messagingSenderId: '354401716290',
    projectId: 'coffee-shop-app-d909c',
    storageBucket: 'coffee-shop-app-d909c.appspot.com',
    iosBundleId: 'com.example.flutterCourse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr2-f_KC2BjnzkfW611zO3VPsRWcAp6_s',
    appId: '1:354401716290:ios:66b94d3eec26ad00ee45db',
    messagingSenderId: '354401716290',
    projectId: 'coffee-shop-app-d909c',
    storageBucket: 'coffee-shop-app-d909c.appspot.com',
    iosBundleId: 'com.example.flutterCourse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCU2K1lzRWP2TiC56gRsPD8TNAaVNP9N6Y',
    appId: '1:354401716290:web:003a0c636709a1bfee45db',
    messagingSenderId: '354401716290',
    projectId: 'coffee-shop-app-d909c',
    authDomain: 'coffee-shop-app-d909c.firebaseapp.com',
    storageBucket: 'coffee-shop-app-d909c.appspot.com',
  );
}
